name: Sync File
on:
  schedule: # Runs at 04:00 UTC every day so that it leaves enough time for the curriculum scraping repo to update (at midnight)
    - cron: "0 4 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Keeps authentication for pushing
      - name: Download curriculum.tsv from source repo
        run: |
          curl -o public/curriculum.tsv https://raw.githubusercontent.com/emile-jn/tiss-curriculum-scraper/main/curriculum.tsv
      - name: Check for changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit changes
        run: |
          git commit -m "Auto-update curriculum.tsv"
          git push

      - name: Trigger deploy workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: "deploy.yml"
          ref: main
